apiVersion: v1
kind: Pod
metadata:
  name: network-test-pod
spec:
  containers:
  - name: debug
    image: mcr.microsoft.com/aks/fundamental/base-ubuntu:v0.0.11
    command: ["/bin/bash", "-c", "sleep 36000"]
    securityContext:
      runAsUser: 1000
      runAsGroup: 3000
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
  restartPolicy: Never
